[colors.bright]
black = "#565575"
blue = "#65b2ff"
cyan = "#63f2f1"
green = "#62d196"
magenta = "#906cff"
red = "#ff5458"
white = "#a6b3cc"
yellow = "#ffb378"

[colors.normal]
black = "#100e23"
blue = "#91ddff"
cyan = "#aaffe4"
green = "#95ffa4"
magenta = "#c991e1"
red = "#ff8080"
white = "#cbe3e7"
yellow = "#ffe9aa"

[colors.primary]
background = "#1b182c"
foreground = "#cbe3e7"
