colors:
  primary:
    background: '#0D0C0E'
    foreground: '#F8F8F2'

  cursor:
    text: '#13012D'
    cursor: '#6E46A4'

  normal:
    black: '#13012D'
    red: '#BF56E3'
    green: '#C6A9F0'
    yellow: '#FFAAFF'
    blue: '#7C16DA'
    magenta: '#9932CC'
    cyan: '#9B6BDF'
    white: '#D5BFEA'

  bright:
    black: '#4d4d4d'
    red: '#ff6e67'
    green: '#5af78e'
    yellow: '#eaf08d'
    blue: '#caa9fa'
    magenta: '#ff92d0'
    cyan: '#aa91e3'
    white: '#e6e6e6'


