colors:
  primary:
    background: "#060606"
    foreground: "#adadad"

  normal:
    black: "#060606"
    red: "#2B2B2B"
    green: "#323232"
    yellow: "#363636"
    blue: "#3A3A3A"
    magenta: "#3D3D3D"
    cyan: "#474747"
    white: "#adadad"

  bright:
    black: "#797979"
    red: "#2B2B2B"
    green: "#323232"
    yellow: "#363636"
    blue: "#3A3A3A"
    magenta: "#3D3D3D"
    cyan: "#474747"
    white: "#adadad"


