layouts:
  - tall
  - wide
  - fullscreen
  - column

# Deal with Floating Windows
float-small-windows: true
floating: 
  - com.apple.systempreferences
  - com.colliderli.iina

# Modify the amethyst relaunch to use x and not z
relaunch-amethyst:
    mod: mod2
    key: x

# Enable focus-follows-mouse
mouse-follows-focus: false
focus-follows-mouse: false

# Add 10px margin around windows
window-margins: true
window-margin-size: 10
